### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jamesanderson16** [andre0707/gcAE#1]
Request for day1976 reverse wherigo solver to be added

Thanks 

James A

**Comment by andre0707** [comment]
Generally I think it makes sense, now that wIgHelper also supports it.

I just tested with https://coord.info/GC9MW5V which uses the day1976 reverse cache. The main problem I see here is recognising the needed codes correct. It was easier with the -Waldmeister- reverse cache, because it is just numbers and they usually are listed next to each other. Day1976 includes letters as well. So just checking for two 5 letter codes could also easily match totally unrelated words instead of the actual codes.
For -Waldmeister- reverse cache, first the listing text is checked for the needed numbers, then the personal note if nothing was found in the listing text.

**_The idea is:_**
For day1976 reverse cache I will check first the personal note and if its empty check the listing text. This way we can enforce to take the right codes. 

I checked a couple wherigos in the area of the above mentioned one and they all seem to have a lot of regular words between the two codes. If that is the case for the majority of these caches, I do not see how we can implement a reliable detection of the codes (besides when they first were copied to the personal note section).

Do you have any thoughts on how to reliable detect the day1976 codes?

**Comment by jamesanderson16** [comment]
Not sure,

I just thought it would be good to have it on there (or at least a disclaimer that it's only waldmaster's solver if it can't be done)

**Comment by andre0707** [comment]
I started with an implementation for the day1976 reverse cache. 
Works perfectly fine so far if the codes are in the personal cache note. Pretty much impossible to detect in the regular listing. 

I’ll definitely add a disclaimer note. 

I’ll also play a little more around, before publishing the update

**Comment by andre0707** [comment]
I added the support for day1976 reverse cache with the next release which is currently in review with the AppStore team.
I also added some disclaimer notes in the wiki and referred to the wiki page in the app itself. 

I think the best way is to copy the reverse codes to the personal note, or use the wIgHelper app for more control when handling the reverse codes.
